apiVersion: v1
kind: ConfigMap
metadata:
  name: csv-to-yaml-config
  namespace: default
  labels:
    app: csv-to-yaml
    app.kubernetes.io/name: csv-to-yaml
    app.kubernetes.io/component: config
data:
  # Application settings
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
  
  # File upload settings
  UPLOAD_FOLDER: "/app/Users"
  ALLOWED_EXTENSIONS: "csv,yml,yaml"
  MAX_CONTENT_LENGTH: "16777216"  # 16MB
  
  # Security settings
  SECRET_KEY: "change-this-in-production"
  SESSION_COOKIE_SECURE: "True"
  SESSION_COOKIE_HTTPONLY: "True"
  SESSION_COOKIE_SAMESITE: "Lax"
  
  # CORS settings
  CORS_ORIGINS: "*"
  CORS_METHODS: "GET,POST,OPTIONS"
  CORS_ALLOW_HEADERS: "Content-Type,Authorization"
  
  # Logging configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Application-specific settings
  DEFAULT_EXPERIMENT_NAME: "default-experiment"
  MAX_FILE_UPLOADS: "10"
  
  # Feature flags
  ENABLE_ARCHITECTURE_UPLOAD: "true"
  ENABLE_CSV_VALIDATION: "true"
  ENABLE_YAML_DOWNLOAD: "true"
