apiVersion: apps/v1
kind: Deployment
metadata:
  name: csv-to-yaml-app
  namespace: csv-to-yaml
  labels:
    app: csv-to-yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csv-to-yaml
  template:
    metadata:
      labels:
        app: csv-to-yaml
    spec:
      containers:
      - name: csv-to-yaml
        image: kerollosadel/csv-to-yaml-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: UPLOAD_FOLDER
          value: /uploads
        volumeMounts:
        - name: uploads
          mountPath: /uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: csv-to-yaml-pvc
