apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: csv-to-yaml-hpa
  namespace: default
  labels:
    app: csv-to-yaml
    app.kubernetes.io/name: csv-to-yaml
    app.kubernetes.io/component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csv-to-yaml-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Uncomment and adjust these settings based on your needs
  # behavior:
  #   scaleDown:
  #     policies:
  #     - type: Pods
  #       value: 1
  #       periodSeconds: 60
  #     stabilizationWindowSeconds: 300
  #     selectPolicy: Min
  #   scaleUp:
  #     policies:
  #     - type: Pods
  #       value: 2
  #       periodSeconds: 60
  #     stabilizationWindowSeconds: 0
  #     selectPolicy: Max
