apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: csv-to-yaml-ingress
  namespace: csv-to-yaml
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: csv-to-yaml-service
            port:
              number: 80
