# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# Add all resources in the current directory
resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml
  - pdb.yaml

# Common labels to add to all resources
commonLabels:
  app: csv-to-yaml
  app.kubernetes.io/name: csv-to-yaml
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: web
  app.kubernetes.io/part-of: csv-to-yaml
  app.kubernetes.io/managed-by: kustomize

# Add prefix/suffix to all resources
namePrefix: ""
nameSuffix: ""

# Image overrides
images:
  - name: csv-to-yaml-app
    newName: your-registry/csv-to-yaml-app
    newTag: latest

# Secret and ConfigMap generator (alternative to separate files)
# secretGenerator:
# - name: csv-to-yaml-secrets
#   literals:
#     - FLASK_SECRET_KEY=change-this-in-production
#   type: Opaque

# configMapGenerator:
# - name: csv-to-yaml-config
#   literals:
#     - FLASK_ENV=production
#     - UPLOAD_FOLDER=/app/Users

# Resource patches (if needed)
# patches:
#   - path: patches/resource-requests.yaml
#   - path: patches/affinity.yaml

# Common annotations to add to all resources
commonAnnotations:
  kubernetes.io/change-cause: "Deployed by Kustomize"
  # Add any other common annotations here

# Configure the kustomize build process
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: csv-to-yaml
  annotations:
    note: Generated by kustomize

# Configure the kustomize build process
configurations:
  - kustomizeconfig.yaml
