apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-to-yaml-pvc
  namespace: csv-to-yaml
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # If your cluster has a default StorageClass, you can omit the storageClassName.
  # Uncomment and set if you need a specific class.
  # storageClassName: standard
