apiVersion: v1
kind: Service
metadata:
  name: csv-to-yaml-service
  namespace: default
  labels:
    app: csv-to-yaml
    app.kubernetes.io/name: csv-to-yaml
    app.kubernetes.io/component: service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:account:certificate/xxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
spec:
  type: ClusterIP
  # For production, you might want to use LoadBalancer instead
  # type: LoadBalancer
  # loadBalancerIP: ""
  # externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9102
    targetPort: 9102
    protocol: TCP
  selector:
    app: csv-to-yaml
    app.kubernetes.io/name: csv-to-yaml
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
  # Uncomment for AWS NLB
  # externalTrafficPolicy: "Local"
  # healthCheckNodePort: 30000
