# @package _global_

model:
  type: lstm
  retrain: true
ts:
  name: model
  version: 1
  enrich: []
  use_covariates: true
  past_variables: []
  future_variables: []
  static_variables: []
train_config:
  batch_size: 32
  max_epochs: 20
model_configs:
  activation: torch.nn.PReLU
  cat_emb_dim: 16
  hidden_RNN: 12
  kernel_size: 3
  kind: lstm
  num_layers_RNN: 3
  optim: torch.optim.Adam
  sum_emb: true
