replicaCount: 1
image:
  repository: hakushaku69/dsipts-p
  pullPolicy: Always
  tag: 3.0.0
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
aim:
  annotations:
    description: Deployment for Aim container
    field.cattle.io/publicEndpoints: '[{"port":30088,"protocol":"TCP","serviceName":"ts-framework:aim-service","allNodes":true}]'
  image:
    repository: hakushaku69/aim-container
    pullPolicy: IfNotPresent
    tag: '1'
  service:
    annotations:
      field.cattle.io/publicEndpoints: '[{"port":30088,"protocol":"TCP","serviceName":"ts-framework:aim-service","allNodes":true}]'
    type: NodePort
    port: 80
    targetPort: 43800
    nodePort: 30088
  persistence:
    enabled: true
    claimName: nfs-aim-pvc
  resources:
    limits:
      cpu: '1'
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  nodeName: srv01
dsipts_p:
  defaults:
    persistence:
      enabled: true
      volumes:
      - name: nfs-ts-framework-pv
        claimName: nfs-ts-framework-pvc
        mounts:
        - mountPath: /DSIPTS-P/output
          subPath: output
        - mountPath: /DSIPTS-P/data
          subPath: instance/uploads/Users/ker#/data
      - name: nfs-aim-pv
        claimName: nfs-aim-pvc
        mounts:
        - mountPath: /aim
    command:
      enabled: true
      run:
      - /bin/sh
      - -c
      modelsToTrain: ''
      args:
      - 'python train.py --config-dir=config_milan --config-name=config_milan;

        sleep infinity'
    configFiles:
      enabled: false
      name: ''
      fromDirectory: Users/ker#/quick_run
      mountPath: /DSIPTS-P/bash_examples/config_milan
  workerGroups:
  - name: a100-workers
    replicaCount: 1
    resources:
      limits:
        cpu: '32'
        ephemeral-storage: 10Gi
        memory: 128Gi
        nvidia.com/gpu: '1'
      requests:
        cpu: '8'
        ephemeral-storage: 1Gi
        memory: 4Gi
        nvidia.com/gpu: '1'
    nodeSelector:
      nvidia.com/gpu.product: NVIDIA-A100-80GB-PCIe
  - name: a1000-workers
    replicaCount: 0
    resources:
      limits:
        cpu: '16'
        memory: 64Gi
        nvidia.com/gpu: '1'
      requests:
        cpu: '4'
        memory: 2Gi
        nvidia.com/gpu: '1'
    nodeSelector:
      nvidia.com/gpu.product: NVIDIA-A1000
  - name: gh200-workers
    replicaCount: 0
    resources:
      limits:
        cpu: '64'
        memory: 512Gi
        nvidia.com/gpu: '1'
      requests:
        cpu: '16'
        memory: 8Gi
        nvidia.com/gpu: '1'
    nodeSelector:
      nvidia.com/gpu.product: NVIDIA-GH200-480GB
  - name: cpu-workers
    replicaCount: 0
    resources:
      limits:
        cpu: '8'
        memory: 16Gi
      requests:
        cpu: '2'
        memory: 2Gi
    nodeSelector: {}
nodeSelector: {}
tolerations: []
affinity: {}
