apiVersion: v1
entries:
  aux-common:
  - apiVersion: v1
    created: "2026-05-08T00:00:42.1939457Z"
    description: Common templates for inclusion in other charts
    digest: f3acc47887d9cabf35c8f27b230119991ab50531cab43c683265ed062d121cdc
    name: aux-common
    urls:
    - charts/aux-common-3.0.0.tgz
    version: 3.0.0
  nonrtric-common:
  - apiVersion: v1
    created: "2026-05-08T00:00:54.8604007Z"
    description: NONRTRIC Common templates for inclusion in other charts
    digest: 28e3186a44c84142d9f1b3d33e8219be865c909adcabb59cd8924eca2a4fcdb4
    name: nonrtric-common
    urls:
    - charts/nonrtric-common-2.0.0.tgz
    version: 2.0.0
  ric-common:
  - apiVersion: v1
    created: "2026-05-08T00:00:10.4667707Z"
    description: Common templates for inclusion in other charts
    digest: f51c9a9560c62b0d1d75b2a9bfb22b6666533b43f6b2c086b84943c8d47a42e4
    name: ric-common
    urls:
    - charts/ric-common-3.3.2.tgz
    version: 3.3.2
generated: "2026-05-08T00:01:53Z"
serverInfo: {}
