# @package _global_

model:
  type: autoformer
  retrain: true
ts:
  name: kbs
  version: 1
  enrich: []
  use_covariates: true
  past_variables: []
  future_variables: []
  static_variables: []
train_config:
  batch_size: 32
  max_epochs: 20
model_configs:
  d_model: 4
  kernel_size: 3
  n_layer_encoder: 2
  n_layer_decoder: 2
  label_len: 4
  n_head: 2
  dropout_rate: 0.5
  factor: 5
  hidden_size: 12
  optim: torch.optim.Adam
  activation: torch.nn.PReLU
  persistence_weight: 0.01
  loss_type: l1
