architecture_files:
- description: YAML training configuration 1 for kfa
  filename: kfa_arch_1.yaml
  type: yaml_training_config
configuration_method: yaml_training_configured
csv_file: name.csv
experiment: kfa
experiment_config_file: kfa_config.yaml
sweeper:
  _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
  direction: minimize
  n_jobs: 2
  n_trials: 4
  params: {}
  sampler:
    _target_: optuna.samplers.TPESampler
    consider_endpoints: false
    consider_magic_clip: true
    consider_prior: true
    multivariate: false
    n_ei_candidates: 24
    n_startup_trials: 10
    prior_weight: 1.0
    seed: 123
    warn_independent_sampling: true
  storage: 'null'
  study_name: kfa
timestamp: '2025-08-04T12:36:39.274904'
user: ker#
