architecture_files:
- description: YAML training configuration 1 for kfa
  filename: kfa_arch_1.yaml
  type: yaml_training_config
configuration_method: yaml_training_configured
csv_file: name.csv
experiment: kfa
experiment_config_file: kfa_config.yaml
timestamp: '2025-08-04T12:36:39.274904'
user: ker#
