# @package _global_

model:
  type: lstm
  retrain: true
ts:
  name: lstm
  version: 1
  enrich: []
  use_covariates: true
  past_variables:
  - 1
  use_future_covariates: false
  future_variables: null
  interpolate: true
model_configs:
  cat_emb_dim: 128
  hidden_RNN: 64
  num_layers_RNN: 2
  kernel_size: 3
  kind: lstm
  sum_emb: true
  use_bn: true
  optim: torch.optim.SGD
  activation: torch.nn.ReLU
  dropout_rate: 0.2
  persistence_weight: 0.01
  loss_type: l1
  remove_last: true
train_config:
  batch_size: 128
  max_epochs: 20
