#!/usr/bin/env python3
"""
xApp Builder: Takes a .pkl model file and builds a Docker image + xApp descriptor.

Flow:
  1. Receive .pkl file path + model params
  2. Generate xApp Python wrapper (loads .pkl, connects to RMR, handles A1 policies)
  3. Generate Dockerfile
  4. Generate xApp descriptor (config-file.json for appmgr)
  5. Build Docker image
  6. Output: image tag + descriptor JSON

Usage:
  python3 build_xapp.py --pkl model.pkl --name traffic-pred --version 1.0.0 --type lstm
  python3 build_xapp.py --demo  (uses a sample .pkl)
"""

import argparse
import json
import os
import subprocess
import sys
import shutil
import pickle
import tempfile

REGISTRY = os.environ.get("XAPP_REGISTRY", "localhost:5000")


def create_sample_pkl(output_path):
    """Create a sample .pkl file for demo purposes."""
    model_data = {
        "model_type": "lstm",
        "layers": [64, 32, 1],
        "input_shape": [24, 7],
        "output_shape": [1],
        "weights": "placeholder_weights",
        "metadata": {
            "trained_on": "milan_traffic_dataset",
            "accuracy": 0.94,
            "framework": "csv-to-yaml-platform"
        }
    }
    with open(output_path, 'wb') as f:
        pickle.dump(model_data, f)
    print(f"  [OK] Sample .pkl created: {output_path}")
    return output_path


def generate_xapp_wrapper(build_dir, model_name, model_type="generic"):
    """
    Generate the Python xApp code that wraps the .pkl model as a proper
    O-RAN ML Model Runner with:
    - RMR (RIC Message Router) messaging
    - A1 policy handler (receives policies from Non-RT RIC)
    - E2 subscription handler (receives KPIs from RAN nodes)
    - Health check HTTP endpoint (for Kubernetes probes)
    - SDL (Shared Data Layer) for state persistence
    - ML prediction pipeline
    """
    code = '''#!/usr/bin/env python3
"""
O-RAN xApp ML Model Runner: {name}
Model Type: {model_type}
Auto-generated by xApp Builder (csv-to-yaml-platform).

This xApp wrapper implements the O-RAN ML Model Runner lifecycle:
  1. Loads the trained .pkl model artifact
  2. Connects to RMR (RIC Message Router) for message-based communication
  3. Subscribes to E2 nodes for KPI data (DRB throughput, PRB usage, etc.)
  4. Receives A1 policies from Non-RT RIC (traffic steering preferences)
  5. Runs ML predictions on incoming data
  6. Sends predictions to downstream consumers (e.g., Near-RT RIC control loops)
  7. Exposes health endpoint for Kubernetes liveness/readiness probes
"""
import pickle
import json
import os
import signal
import sys
import time
import threading
import logging
from http.server import HTTPServer, BaseHTTPRequestHandler
from datetime import datetime

# ============================================================
# Configuration (from environment variables or defaults)
# ============================================================
MODEL_PATH = os.environ.get("MODEL_PATH", "/app/model.pkl")
RMR_PORT = int(os.environ.get("RMR_PORT", "4560"))
RMR_SEED_RT = os.environ.get("RMR_SEED_RT", "/app/route_table.rt")
HEALTH_PORT = int(os.environ.get("HEALTH_PORT", "8080"))
A1_POLICY_TYPE_ID = int(os.environ.get("A1_POLICY_TYPE_ID", "20008"))
SDL_NAMESPACE = os.environ.get("SDL_NAMESPACE", "xapp_{name}")
XAPP_NAME = "{name}"
MODEL_TYPE = "{model_type}"
LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO")

# O-RAN xApp descriptor: the onboarder mounts config-file.json into the container
# and points XAPP_DESCRIPTOR_PATH at its directory. The 'controls' section carries
# the framework config (model type, hyperparameters, timeseries, training).
XAPP_DESCRIPTOR_PATH = os.environ.get("XAPP_DESCRIPTOR_PATH", "/opt/ric/config")


def load_controls():
    """Load the 'controls' section from the mounted xApp descriptor (config-file.json)."""
    for path in (
        os.path.join(XAPP_DESCRIPTOR_PATH, "config-file.json"),
        "/app/config-file.json",
    ):
        try:
            with open(path) as f:
                desc = json.load(f)
            return desc.get("controls", {{}})
        except FileNotFoundError:
            continue
        except Exception:
            continue
    return {{}}

# Logging setup
logging.basicConfig(
    level=getattr(logging, LOG_LEVEL),
    format='[%(asctime)s] [xApp:%(name)s] %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(XAPP_NAME)

# ============================================================
# RMR Message Types (O-RAN standard)
# ============================================================
RMR_MSG_TYPES = {{
    "A1_POLICY_REQ": 20010,
    "A1_POLICY_RESP": 20011,
    "A1_POLICY_QUERY": 20012,
    "RIC_SUB_REQ": 12011,
    "RIC_SUB_RESP": 12012,
    "RIC_SUB_DEL_REQ": 12020,
    "RIC_INDICATION": 12050,
    "RIC_CONTROL_REQ": 12040,
    "RIC_CONTROL_ACK": 12041,
    "HEALTH_CHECK_REQ": 100,
    "HEALTH_CHECK_RESP": 101,
    "PREDICTION_OUTPUT": 30000,
}}


# ============================================================
# SDL (Shared Data Layer) - In-memory fallback
# ============================================================
class SharedDataLayer:
    """
    Shared Data Layer interface for xApp state persistence.
    Uses Redis/DBAAS in production, in-memory dict for standalone mode.
    """
    def __init__(self, namespace):
        self.namespace = namespace
        self._store = {{}}
        self._connected = False
        try:
            import redis
            self._redis = redis.Redis(
                host=os.environ.get("DBAAS_SERVICE_HOST", "localhost"),
                port=int(os.environ.get("DBAAS_SERVICE_PORT", "6379"))
            )
            self._redis.ping()
            self._connected = True
            logger.info("SDL connected to Redis/DBAAS")
        except Exception:
            logger.info("SDL using in-memory store (Redis not available)")
            self._redis = None

    def set(self, key, value):
        full_key = f"{{self.namespace}}:{{key}}"
        if self._connected:
            self._redis.set(full_key, json.dumps(value))
        else:
            self._store[full_key] = value

    def get(self, key):
        full_key = f"{{self.namespace}}:{{key}}"
        if self._connected:
            val = self._redis.get(full_key)
            return json.loads(val) if val else None
        return self._store.get(full_key)

    def delete(self, key):
        full_key = f"{{self.namespace}}:{{key}}"
        if self._connected:
            self._redis.delete(full_key)
        else:
            self._store.pop(full_key, None)


# ============================================================
# RMR Interface (RIC Message Router)
# ============================================================
class RMRInterface:
    """
    RMR (RIC Message Router) interface for xApp communication.
    Handles message send/receive with the Near-RT RIC platform.
    Falls back to socket-based messaging if ricxappframe not available.
    """
    def __init__(self, port):
        self.port = port
        self.mrc = None  # RMR message router context
        self._ready = False
        self._init_rmr()

    def _init_rmr(self):
        try:
            import ricxappframe.rmr as rmr
            self.mrc = rmr.rmr_init(str(self.port).encode(), rmr.RMR_MAX_RCV_BYTES, 0x00)
            while rmr.rmr_ready(self.mrc) == 0:
                time.sleep(0.1)
            self._ready = True
            logger.info(f"RMR initialized on port {{self.port}}")
        except ImportError:
            logger.warning("ricxappframe not installed - using standalone RMR stub")
            self._ready = True  # Stub mode
        except Exception as e:
            logger.error(f"RMR init failed: {{e}}")

    @property
    def ready(self):
        return self._ready

    def receive(self, timeout_ms=500):
        """Receive a message from RMR. Returns (msg_type, payload) or None."""
        if self.mrc is None:
            return None
        try:
            import ricxappframe.rmr as rmr
            sbuf = rmr.rmr_alloc_msg(self.mrc, 4096)
            sbuf = rmr.rmr_torcv_msg(self.mrc, sbuf, timeout_ms)
            if sbuf.contents.state == 0:  # RMR_OK
                msg_type = sbuf.contents.mtype
                payload = rmr.rmr_get_src(sbuf).decode()
                return (msg_type, payload)
            rmr.rmr_free_msg(sbuf)
        except Exception:
            pass
        return None

    def send(self, msg_type, payload, meid=""):
        """Send a message via RMR."""
        if self.mrc is None:
            logger.debug(f"RMR stub: send type={{msg_type}} payload={{payload[:100]}}")
            return True
        try:
            import ricxappframe.rmr as rmr
            sbuf = rmr.rmr_alloc_msg(self.mrc, len(payload))
            sbuf.contents.mtype = msg_type
            sbuf.contents.payload = payload.encode()
            sbuf.contents.len = len(payload)
            sbuf = rmr.rmr_send_msg(self.mrc, sbuf)
            success = sbuf.contents.state == 0
            rmr.rmr_free_msg(sbuf)
            return success
        except Exception as e:
            logger.error(f"RMR send failed: {{e}}")
            return False


# ============================================================
# Health Check HTTP Server
# ============================================================
class HealthHandler(BaseHTTPRequestHandler):
    """HTTP handler for Kubernetes liveness/readiness probes."""
    xapp_ref = None

    def do_GET(self):
        if self.path == "/health" or self.path == "/ready":
            status = self.server.xapp_ref.get_health_status() if self.server.xapp_ref else {{"status": "unknown"}}
            code = 200 if status.get("healthy") else 503
            self.send_response(code)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps(status).encode())
        elif self.path == "/metrics":
            metrics = self.server.xapp_ref.get_metrics() if self.server.xapp_ref else {{}}
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps(metrics).encode())
        else:
            self.send_response(404)
            self.end_headers()

    def log_message(self, format, *args):
        pass  # Suppress health check logs


# ============================================================
# ML Model Runner (Main xApp Class)
# ============================================================
class MLModelRunner:
    """
    O-RAN ML Model Runner xApp.
    Implements the full lifecycle: load model, subscribe to data,
    receive policies, run predictions, report results.
    """

    def __init__(self):
        self.model = None
        self.model_metadata = {{}}
        self.hyperparameters = {{}}
        self.running = True
        self.healthy = False
        self.start_time = datetime.utcnow()

        # Statistics
        self.stats = {{
            "predictions_made": 0,
            "a1_policies_received": 0,
            "e2_indications_received": 0,
            "errors": 0,
            "last_prediction_time": None,
        }}

        # Active A1 policies
        self.active_policies = {{}}

        # Runtime config from the xApp descriptor 'controls' section
        self.controls = load_controls()
        self.model_type = self.controls.get("model_type", MODEL_TYPE)
        self.hyperparameters = self.controls.get("hyperparameters", {{}})

        # Signal handlers
        signal.signal(signal.SIGTERM, self._shutdown)
        signal.signal(signal.SIGINT, self._shutdown)

        # Initialize components
        logger.info(f"Initializing ML Model Runner: {{XAPP_NAME}} ({{self.model_type}})")
        logger.info(f"Controls loaded: {{len(self.controls)}} keys, {{len(self.hyperparameters)}} hyperparameters")
        self.sdl = SharedDataLayer(SDL_NAMESPACE)
        self.rmr = RMRInterface(RMR_PORT)
        self._start_health_server()

    def _shutdown(self, signum, frame):
        logger.info(f"Received signal {{signum}}, initiating graceful shutdown...")
        self.running = False

    def _start_health_server(self):
        """Start HTTP health check server in background thread."""
        def serve():
            server = HTTPServer(("0.0.0.0", HEALTH_PORT), HealthHandler)
            server.xapp_ref = self
            server.timeout = 1
            while self.running:
                server.handle_request()
        t = threading.Thread(target=serve, daemon=True)
        t.start()
        logger.info(f"Health endpoint started on port {{HEALTH_PORT}}")

    # ---- Model Loading ----
    def load_model(self):
        """Load the trained ML model from the .pkl artifact."""
        logger.info(f"Loading model from {{MODEL_PATH}}")
        try:
            with open(MODEL_PATH, "rb") as f:
                artifact = pickle.load(f)

            if isinstance(artifact, dict):
                self.model = artifact
                self.model_metadata = {{
                    "model_type": artifact.get("model_type", MODEL_TYPE),
                    "version": artifact.get("version", "unknown"),
                    "framework": artifact.get("framework", "unknown"),
                    "created_at": artifact.get("created_at", "unknown"),
                }}
                self.hyperparameters = artifact.get("hyperparameters", {{}})
            else:
                # Raw model object (e.g., sklearn, torch)
                self.model = artifact
                self.model_metadata = {{"model_type": MODEL_TYPE}}

            logger.info(f"Model loaded: {{self.model_metadata}}")
            logger.info(f"Hyperparameters: {{len(self.hyperparameters)}} params")
            self.healthy = True
            self.sdl.set("model_status", {{"loaded": True, "type": MODEL_TYPE}})
            return True
        except Exception as e:
            logger.error(f"Model loading failed: {{e}}")
            self.stats["errors"] += 1
            return False

    # ---- A1 Policy Handler ----
    def handle_a1_policy(self, payload):
        """
        Handle A1 policy updates from Non-RT RIC.
        Policy types: Traffic Steering, QoS, Resource Allocation.
        """
        try:
            policy = json.loads(payload) if isinstance(payload, str) else payload
            policy_id = policy.get("policy_id", "unknown")
            policy_type = policy.get("policy_type_id", A1_POLICY_TYPE_ID)

            logger.info(f"A1 policy received: id={{policy_id}}, type={{policy_type}}")
            self.stats["a1_policies_received"] += 1

            # Store active policy
            self.active_policies[policy_id] = {{
                "policy": policy,
                "received_at": datetime.utcnow().isoformat(),
                "status": "ENFORCED"
            }}
            self.sdl.set(f"policy_{{policy_id}}", self.active_policies[policy_id])

            # Send ACK back via RMR
            ack = {{
                "policy_type_id": policy_type,
                "policy_id": policy_id,
                "handler_id": XAPP_NAME,
                "status": "OK"
            }}
            self.rmr.send(RMR_MSG_TYPES["A1_POLICY_RESP"], json.dumps(ack))
            return ack
        except Exception as e:
            logger.error(f"A1 policy handling error: {{e}}")
            self.stats["errors"] += 1
            return {{"status": "ERROR", "reason": str(e)}}

    # ---- E2 Indication Handler ----
    def handle_e2_indication(self, payload):
        """
        Handle E2 indications (KPI data from RAN nodes).
        Processes metrics and triggers ML prediction.
        """
        try:
            indication = json.loads(payload) if isinstance(payload, str) else payload
            self.stats["e2_indications_received"] += 1

            # Extract KPI data
            kpi_data = indication.get("indicationMessage", {{}})
            cell_id = indication.get("cellGlobalId", "unknown")

            logger.debug(f"E2 indication from cell {{cell_id}}: {{list(kpi_data.keys())}}")

            # Run prediction on the KPI data
            prediction = self.predict(kpi_data)

            # Send prediction result via RMR
            result_msg = {{
                "xapp": XAPP_NAME,
                "model_type": self.model_type,
                "cell_id": cell_id,
                "prediction": prediction,
                "timestamp": datetime.utcnow().isoformat(),
                "active_policies": list(self.active_policies.keys())
            }}
            self.rmr.send(RMR_MSG_TYPES["PREDICTION_OUTPUT"], json.dumps(result_msg))

            return prediction
        except Exception as e:
            logger.error(f"E2 indication handling error: {{e}}")
            self.stats["errors"] += 1
            return None

    # ---- ML Prediction ----
    def predict(self, input_data):
        """
        Run ML prediction using the loaded model.
        Input: KPI metrics dict (from E2 or direct call)
        Output: prediction result dict
        """
        if self.model is None:
            return {{"error": "Model not loaded", "status": "FAIL"}}

        try:
            self.stats["predictions_made"] += 1
            self.stats["last_prediction_time"] = datetime.utcnow().isoformat()

            # Build prediction result
            # In production, this would invoke the actual model inference
            model_configs = self.model.get("model_configs", {{}}) if isinstance(self.model, dict) else {{}}
            
            prediction_result = {{
                "model": XAPP_NAME,
                "model_type": self.model_type,
                "input_features": list(input_data.keys()) if isinstance(input_data, dict) else [],
                "prediction": {{
                    "value": 0.0,
                    "confidence": 0.95,
                    "horizon": model_configs.get("pred_len", 96),
                }},
                "hyperparameters_used": self.hyperparameters,
                "timestamp": datetime.utcnow().isoformat(),
                "status": "SUCCESS"
            }}

            # Apply active A1 policies to prediction
            if self.active_policies:
                prediction_result["policies_applied"] = list(self.active_policies.keys())

            self.sdl.set("last_prediction", prediction_result)
            return prediction_result
        except Exception as e:
            logger.error(f"Prediction error: {{e}}")
            self.stats["errors"] += 1
            return {{"error": str(e), "status": "FAIL"}}

    # ---- Health & Metrics ----
    def get_health_status(self):
        """Return health status for Kubernetes probes."""
        uptime = (datetime.utcnow() - self.start_time).total_seconds()
        return {{
            "healthy": self.healthy and self.running,
            "xapp": XAPP_NAME,
            "model_type": self.model_type,
            "model_loaded": self.model is not None,
            "rmr_ready": self.rmr.ready,
            "uptime_seconds": round(uptime, 1),
            "predictions_made": self.stats["predictions_made"],
        }}

    def get_metrics(self):
        """Return Prometheus-compatible metrics."""
        return {{
            "xapp_name": XAPP_NAME,
            "model_type": MODEL_TYPE,
            **self.stats,
            "active_policies_count": len(self.active_policies),
            "uptime_seconds": (datetime.utcnow() - self.start_time).total_seconds(),
        }}

    # ---- E2 Subscription ----
    def subscribe_e2(self):
        """Subscribe to E2 nodes for KPI data."""
        sub_req = {{
            "ClientEndpoint": {{"Host": "", "HTTPPort": HEALTH_PORT, "RMRPort": RMR_PORT}},
            "Meid": "gnb_001",
            "RANFunctionID": 1,
            "SubscriptionDetails": [{{
                "XappEventInstanceId": 1,
                "EventTriggers": [1],
                "ActionToBeSetupList": [{{
                    "ActionID": 1,
                    "ActionType": "report",
                    "ActionDefinition": [1],
                    "SubsequentAction": {{"SubsequentActionType": "continue", "TimeToWait": "w10ms"}}
                }}]
            }}]
        }}
        self.rmr.send(RMR_MSG_TYPES["RIC_SUB_REQ"], json.dumps(sub_req))
        logger.info("E2 subscription request sent")

    # ---- Main Loop ----
    def run(self):
        """Main xApp execution loop."""
        logger.info("=" * 60)
        logger.info(f"  O-RAN ML Model Runner: {{XAPP_NAME}}")
        logger.info(f"  Model Type: {{MODEL_TYPE}}")
        logger.info(f"  RMR Port: {{RMR_PORT}}")
        logger.info(f"  Health Port: {{HEALTH_PORT}}")
        logger.info("=" * 60)

        # Load model
        if not self.load_model():
            logger.error("Failed to load model, exiting")
            sys.exit(1)

        # Subscribe to E2 data
        self.subscribe_e2()

        logger.info(f"xApp {{XAPP_NAME}} is running. Waiting for messages...")

        # Message processing loop
        while self.running:
            msg = self.rmr.receive(timeout_ms=500)
            if msg:
                msg_type, payload = msg
                if msg_type == RMR_MSG_TYPES["A1_POLICY_REQ"]:
                    self.handle_a1_policy(payload)
                elif msg_type == RMR_MSG_TYPES["RIC_INDICATION"]:
                    self.handle_e2_indication(payload)
                elif msg_type == RMR_MSG_TYPES["HEALTH_CHECK_REQ"]:
                    self.rmr.send(RMR_MSG_TYPES["HEALTH_CHECK_RESP"],
                                  json.dumps(self.get_health_status()))
                elif msg_type == RMR_MSG_TYPES["RIC_SUB_RESP"]:
                    logger.info("E2 subscription confirmed")
                else:
                    logger.debug(f"Unknown message type: {{msg_type}}")
            time.sleep(0.01)  # Prevent busy-wait

        # Graceful shutdown
        logger.info("Shutting down...")
        self.sdl.set("shutdown_time", datetime.utcnow().isoformat())
        logger.info(f"Final stats: {{json.dumps(self.stats)}}")
        logger.info("xApp shutdown complete.")


if __name__ == "__main__":
    xapp = MLModelRunner()
    xapp.run()
'''.format(name=model_name, model_type=model_type)
    path = os.path.join(build_dir, "xapp_main.py")
    with open(path, 'w') as f:
        f.write(code)
    return path


def generate_dockerfile(build_dir, model_name):
    """Generate Dockerfile for the xApp with O-RAN RIC dependencies."""
    dockerfile = f'''FROM python:3.11-slim

LABEL name="{model_name}" \\
      description="O-RAN ML Model Runner xApp - auto-built by xApp Builder" \\
      org.o-ran-sc.xapp.name="{model_name}" \\
      org.o-ran-sc.xapp.component="ml-model-runner"

WORKDIR /app

# Install system dependencies for RMR
RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy xApp code and model
COPY xapp_main.py /app/xapp_main.py
COPY model.pkl /app/model.pkl
COPY route_table.rt /app/route_table.rt
COPY config-file.json /app/config-file.json

# Environment configuration
ENV MODEL_PATH=/app/model.pkl
ENV RMR_PORT=4560
ENV RMR_SEED_RT=/app/route_table.rt
ENV HEALTH_PORT=8080
ENV XAPP_DESCRIPTOR_PATH=/app
ENV LOG_LEVEL=INFO

# Health check
HEALTHCHECK --interval=15s --timeout=5s --start-period=10s --retries=3 \\
    CMD curl -f http://localhost:8080/health || exit 1

# Expose ports: RMR data + health check
EXPOSE 4560 8080

CMD ["python3", "/app/xapp_main.py"]
'''
    path = os.path.join(build_dir, "Dockerfile")
    with open(path, 'w') as f:
        f.write(dockerfile)

    # Generate requirements.txt for the xApp container
    requirements = """# O-RAN xApp dependencies
# ricxappframe>=3.0.0  # Uncomment when deploying to real RIC platform
redis>=4.0.0
"""
    req_path = os.path.join(build_dir, "requirements.txt")
    with open(req_path, 'w') as f:
        f.write(requirements)

    # Generate RMR route table
    route_table = f"""newrt|start
mse|20010|{model_name}|{model_name}:4560
mse|12050|{model_name}|{model_name}:4560
mse|100|{model_name}|{model_name}:4560
newrt|end
"""
    rt_path = os.path.join(build_dir, "route_table.rt")
    with open(rt_path, 'w') as f:
        f.write(route_table)

    return path


def generate_xapp_descriptor(build_dir, model_name, model_version, model_type, image_tag):
    """Generate the xApp descriptor (config-file.json) for appmgr."""
    descriptor = {
        "xapp_name": model_name,
        "version": model_version,
        "containers": [
            {
                "name": model_name,
                "image": {
                    "registry": REGISTRY,
                    "name": f"xapps/{model_name}",
                    "tag": model_version
                }
            }
        ],
        "messaging": {
            "ports": [
                {
                    "name": "rmr-data",
                    "container": model_name,
                    "port": 4560,
                    "rxMessages": ["A1_POLICY_REQ", "RIC_SUB_RESP"],
                    "txMessages": ["A1_POLICY_RESP", "RIC_SUB_REQ", "RIC_INDICATION"],
                    "policies": [20008]
                }
            ]
        },
        "controls": {
            "model_type": model_type,
            "model_version": model_version,
            "a1_policy": {
                "policy_type_id": 20008,
                "types": ["ORAN_TrafficSteeringPreference_2.0.0"]
            },
            "hyperparameters": {}
        }
    }
    path = os.path.join(build_dir, "config-file.json")
    with open(path, 'w') as f:
        json.dump(descriptor, f, indent=2)

    # Generate the matching controls schema (the O-RAN onboarder requires a
    # schema whenever the descriptor declares a non-empty controls section).
    schema = generate_controls_schema(descriptor["controls"])
    schema_path = os.path.join(build_dir, "schema.json")
    with open(schema_path, 'w') as f:
        json.dump(schema, f, indent=2)
    return path, descriptor


def _json_schema_from_value(value):
    """Infer a draft-07 JSON Schema fragment from a Python value."""
    if isinstance(value, bool):
        return {"type": "boolean"}
    if isinstance(value, int):
        return {"type": "integer"}
    if isinstance(value, float):
        return {"type": "number"}
    if isinstance(value, str):
        return {"type": "string"}
    if isinstance(value, list):
        return {"type": "array", "items": _json_schema_from_value(value[0])} if value else {"type": "array"}
    if isinstance(value, dict):
        return {
            "type": "object",
            "properties": {k: _json_schema_from_value(v) for k, v in value.items()},
            "required": list(value.keys())
        }
    return {}


def generate_controls_schema(controls):
    """Generate the draft-07 controls schema that validates the controls section."""
    schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "#/controls",
        "title": "Controls Section Schema",
    }
    schema.update(_json_schema_from_value(controls))
    return schema


def generate_helm_chart(build_dir, model_name, model_version, image_tag):
    """Generate a minimal Helm chart for deploying the xApp."""
    chart_dir = os.path.join(build_dir, "helm", model_name)
    templates_dir = os.path.join(chart_dir, "templates")
    os.makedirs(templates_dir, exist_ok=True)

    # Chart.yaml
    with open(os.path.join(chart_dir, "Chart.yaml"), 'w') as f:
        f.write(f"""apiVersion: v2
name: {model_name}
description: ML xApp - {model_name}
version: {model_version}
appVersion: "{model_version}"
""")

    # values.yaml
    repo = image_tag.rsplit(':', 1)[0]
    with open(os.path.join(chart_dir, "values.yaml"), 'w') as f:
        f.write(f"""image:
  repository: {repo}
  tag: "{model_version}"
  pullPolicy: IfNotPresent
replicaCount: 1
rmrPort: 4560
healthPort: 8080
""")

    # deployment.yaml template
    with open(os.path.join(templates_dir, "deployment.yaml"), 'w') as f:
        f.write("""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.rmrPort }}
          name: rmr-data
        - containerPort: {{ .Values.healthPort }}
          name: health
        env:
        - name: MODEL_PATH
          value: "/app/model.pkl"
        - name: RMR_PORT
          value: "{{ .Values.rmrPort }}"
        - name: HEALTH_PORT
          value: "{{ .Values.healthPort }}"
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.healthPort }}
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ready
            port: {{ .Values.healthPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
""")

    # service.yaml template
    with open(os.path.join(templates_dir, "service.yaml"), 'w') as f:
        f.write("""apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - port: {{ .Values.rmrPort }}
    targetPort: rmr-data
    name: rmr-data
""")

    return chart_dir


def build_docker_image(build_dir, image_tag):
    """Build the Docker image using Minikube's Docker daemon."""
    print(f"  [BUILD] Building Docker image: {image_tag}")
    # Use minikube's docker daemon so the image is available inside the cluster
    env_cmd = subprocess.run(
        ["minikube", "-p", "kero-ric", "docker-env", "--shell", "bash"],
        capture_output=True, text=True
    )
    # Parse the env vars
    env = os.environ.copy()
    for line in env_cmd.stdout.strip().split('\n'):
        if line.startswith('export '):
            parts = line.replace('export ', '').split('=', 1)
            if len(parts) == 2:
                key = parts[0]
                val = parts[1].strip('"')
                env[key] = val

    result = subprocess.run(
        ["docker", "build", "-t", image_tag, build_dir],
        env=env, capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"  [FAIL] Docker build failed: {result.stderr}")
        return False
    print(f"  [OK] Image built: {image_tag}")
    return True


def main():
    parser = argparse.ArgumentParser(description="xApp Builder - wrap .pkl into xApp Docker image")
    parser.add_argument("--pkl", help="Path to the .pkl model file")
    parser.add_argument("--name", default="ml-xapp", help="xApp name")
    parser.add_argument("--version", default="1.0.0", help="xApp version")
    parser.add_argument("--type", default="generic", help="Model type (lstm, autoformer, etc.)")
    parser.add_argument("--demo", action="store_true", help="Run with a sample .pkl")
    parser.add_argument("--no-build", action="store_true", help="Generate files only, don't build image")
    parser.add_argument("--output-dir", default=None, help="Output directory for build artifacts")
    args = parser.parse_args()

    print("=" * 60)
    print("  xApp Builder: .pkl -> Docker Image + Descriptor")
    print("=" * 60)
    print()

    # Set up build directory
    if args.output_dir:
        build_dir = args.output_dir
        os.makedirs(build_dir, exist_ok=True)
    else:
        build_dir = tempfile.mkdtemp(prefix="xapp-build-")

    # Handle .pkl file
    if args.demo:
        args.name = "traffic-prediction-lstm"
        args.type = "lstm"
        args.version = "1.0.0"
        pkl_path = os.path.join(build_dir, "model.pkl")
        create_sample_pkl(pkl_path)
    elif args.pkl:
        pkl_path = os.path.abspath(args.pkl)
        if not os.path.exists(pkl_path):
            print(f"  [FAIL] .pkl file not found: {pkl_path}")
            sys.exit(1)
        shutil.copy2(pkl_path, os.path.join(build_dir, "model.pkl"))
    else:
        print("  [FAIL] Provide --pkl <path> or --demo")
        sys.exit(1)

    image_tag = f"{REGISTRY}/xapps/{args.name}:{args.version}"

    print(f"  [INPUT]")
    print(f"    Model: {args.name} v{args.version}")
    print(f"    Type: {args.type}")
    print(f"    PKL: {pkl_path}")
    print()

    # Step 1: Generate xApp wrapper (ML Model Runner)
    print("  [1/5] Generating xApp ML Model Runner wrapper...")
    generate_xapp_wrapper(build_dir, args.name, args.type)

    # Step 2: Generate Dockerfile
    print("  [2/5] Generating Dockerfile...")
    generate_dockerfile(build_dir, args.name)

    # Step 3: Generate xApp descriptor
    print("  [3/5] Generating xApp descriptor (config-file.json)...")
    desc_path, descriptor = generate_xapp_descriptor(
        build_dir, args.name, args.version, args.type, image_tag
    )

    # Step 4: Generate Helm chart
    print("  [4/5] Generating Helm chart...")
    chart_dir = generate_helm_chart(build_dir, args.name, args.version, image_tag)

    # Step 5: Build Docker image
    if not args.no_build:
        print("  [5/5] Building Docker image (inside Minikube)...")
        success = build_docker_image(build_dir, image_tag)
        if not success:
            print("\n  [WARN] Image build failed. Files are still in: " + build_dir)
    else:
        print("  [5/5] Skipping Docker build (--no-build)")
        success = True

    # Summary
    print()
    print("=" * 60)
    print("  BUILD COMPLETE")
    print("=" * 60)
    print(f"  Image tag:      {image_tag}")
    print(f"  Descriptor:     {desc_path}")
    print(f"  Helm chart:     {chart_dir}")
    print(f"  Build dir:      {build_dir}")
    print()
    print("  xApp Descriptor (config-file.json):")
    print(json.dumps(descriptor, indent=4))
    print()
    print("  Next steps:")
    print(f"    1. Register in catalog:  curl -X POST http://localhost:8080/models \\")
    print(f"         -H 'Content-Type: application/json' -d @{desc_path}")
    print(f"    2. Deploy via Helm:      helm install {args.name} {chart_dir} --namespace ricxapp")
    print("=" * 60)

    return build_dir, image_tag, descriptor


if __name__ == "__main__":
    main()
